modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    credits = "AvocadoSpud [Block Texture], KingRolly [Mod Name]"
    description='''${mod_description}'''
    #logoFile="examplemod.png" #optional
    displayTest = "MATCH_VERSION"

[[mixins]]
    config="ditr.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"